### ISSUE TITLE
Similar plugin exists, possibly merge APIs

### ISSUE THREAD

**Issue by devinivy** [Pencroff/hapi-waterline#1]
Hi!  We've both created a very similar plugin– mine is called [dogwater](https://github.com/devinivy/dogwater).  Maybe we can work-out a merging of features or something.  I'm not sure the best way to approach this, honestly!  I'd love to foster a Waterline community within the hapi ecosystem–I think it could be very great for the larger Waterline community, and also great for the hapi ecosystem, which doesn't have many offerings for ORM integrations.  To start, here's a rundown of the differences between our plugins.  Feel free to include anything I've missed.

hapi-waterline does, dogwater doesn't
- expose the ORM itself and databases directly on the plugin
- decorate the server with a `getModel` method
- allow a directory or array of directories to be passed for model definitions
- provide a reset method for testing

dogwater does, hapi-waterline doesn't
- have an option to load fixtures
- expose models to request object
- allow adapters to be passed as strings for use with rejoice
- allow multiple Waterline instantiations to exist (on different servers, for example)
- support and have tests for both hapi7 and hapi8
- work with other hapi plugins like [bedwetter](https://github.com/devinivy/bedwetter)
- decorate the server with a `getWaterline` method
- allow a file or array to be passed for model definitions
- optionally pass Waterline to model definitions for use in lifecycle callbacks

Also, here are some Waterline/hapi plugins of mine that you might find useful,
https://www.npmjs.com/package/bedwetter
https://www.npmjs.com/package/waterline-to-boom
https://www.npmjs.com/package/waterline-fixtures

**Comment by Pencroff** [comment]
Hi! Sorry, didn't see your suggestion. Let's talk about when I return from my holiday. Nice to have this kind of suggestions!

**Comment by devinivy** [comment]
Great, let's chat when you return!

**Comment by Pencroff** [comment]
Hi, Devin.
I have returned and ready to chat about our projects.
Do you have any suggestion for merging and road map for future?

**Comment by devinivy** [comment]
Hi!  Sorry for the delay on my end.
We should take the best features of both of our plugins and settle on a clean API.

For example, I really like that hapi-waterline exposes the ORM, and I think that's cleaner than dogwater's approach of exposing the collections then providing a `getWaterline` method on the server.  But I do like that dogwater exposes the model on the request object for the sake of convenience.

In dogwater, the module itself doesnt hold onto any waterline instances.  I thought it was safer that way in case dogwater gets registered to multiple servers.  hapi-waterline takes the approach of holding on to waterline, which allows nifty features that can access the ORM using `require` (currently this just includes your `reset` method).  We should evaluate which approach is more worthwhile.

Past that there are small things...
It would be nice to support hapi7 and hapi8 with tests like dogwater does.
It would be nice to be able to include collections using directories (like hapi-waterline) and using files (like dogwater).

One big question that we'll have to figure-out if we do merge projects: which project do we merge into?  My inclination is to merge hapi-waterline features into dogwater since dogwater has a few more features and includes tests for hapi7+hapi8.  It also might have a bit more adoption because it has been around longer and is linked-to on the hapi website.  But perhaps I'm a bit biased!  Very willing to hear what you think about this.  In either case, can we agree to be co-owners of the project?
