### ISSUE TITLE
Support for hapi v17

### ISSUE THREAD

**Issue by mickelindahl** [Pencroff/hapi-waterline#3]
Hi, 

Thanks for a simple and good plugin :-). Love it

Hapi have released a version v17 where they among others remove all callback functionality and replace is with async/await, see the [change log](https://github.com/hapijs/hapi/issues/3658). This is a breaking change making. Thus the plugin needs to be updated to accommodate these changes. I can do this and the submit a pull request. Would that be okey for you? 

Cheers
Mikael

**Comment by tswayne** [comment]
Hey @mickelindahl - it looks like this repo is long abandoned.  But, I have remade this plugin for hapi v17 / waterline v13 [here](https://github.com/tswayne/hapi-water).  Hope it works for you!

**Comment by Pencroff** [comment]
The update is in progress and should be available on NPM soon

**Comment by mickelindahl** [comment]
Cool :-)

**Comment by Pencroff** [comment]
Published [new version](https://www.npmjs.com/package/hapi-waterline)
